server:
  port: 8001 #监控面板页面端口

turbine:
  stream:
    port: 8989 #指定turbine请求端口

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
  security:
    enabled: false #敏感端口无权访问，设置false则都可访问（acturcor）

spring:
  profiles: pro
  boot:
    admin:
      contextPath: /monitor
      turbine:
        clusters: "default"
        url: http://localhost:8989/turbine.stream
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema[0]: classpath:/zipkin.sql
    initialize: false
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  sleuth:
    enabled: true

zipkin:
  ui:
    enabled: true
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: guest
      password: guest
      queue: rrdloan.queue.account.sleuth.zipkin #默认值为zipkin
      concurrency: 1
  storage:
    type: mysql



security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true

