spring:
  profiles: dev
#  # 重试机制
#  cloud:
#    loadbalancer:
#      retry:
#       enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest
  zipkin:
    enabled: true
    sender:
      type: rabbit
    rabbitmq:
      queue: rrdloan.queue.account.sleuth.zipkin
  sleuth:
    web:
      skip-pattern: /turbine.stream|/turbine.*|api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream
    scheduled:
      enabled: false
#      skip-pattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask

server:
  port: 4000

zuul:
  ignoredServices: '*'
  routes:
    service-a:
      path: /sa/**
      serviceId: service-a
    service-b:
      path: /sb/**
      serviceId: service-b
  host:
    connect-timeout-millis: 25000
    socket-timeout-millis: 5000

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
management:
  security:
    enabled: false

ribbon:
  ReadTimeout: 4000
  SocketTimeout: 4000
  #  # 对所有操作请求都进行重试
  #  OkToRetryOnAllOperations : true
  #  # 切换实例的重试次数
  #  MaxAutoRetriesNextServer : 2
  #  # 对当前实例的重试次数
  #  MaxAutoRetries : 1

#service-b:
#  ribbon:
#    # 对所有操作请求都进行重试
#    OkToRetryOnAllOperations : true
#    # 切换实例的重试次数
#    MaxAutoRetriesNextServer : 2
#    # 对当前实例的重试次数
#    MaxAutoRetries : 1
#    ReadTimeout: 4000
#    SocketTimeout: 4000



