server:
  port: 8001

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  profiles: dev
  sleuth:
    enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest
  cloud:
    #spring-cloud-stream
    stream:
      bindings:
        turbineStreamInput:
          destination: springCloudHystrixStream #指定turbine的exchange（默认值）
          group: turbine #指定turbine消费队列（持久化）

turbine:
  stream:
    port: 8989
  combine-host-port: true
management:
  security:
    enabled: false
