server:
  port: 6001

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  profiles: dev
  application:
    name: zipkin-server
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    schema[0]: classpath:/zipkin.sql
    initialize: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest

zipkin:
  storage:
    type: mysql
    StorageComponent: mysql