#请求携带账户密码
spring:
  boot:
    admin:
      client:
        metadata:
          user.name: admin
          user.password: admin
  #zipkin客户端配置
  zipkin:
    enabled: true
    sender:
      type: rabbit
    rabbitmq:
      queue: queue.zipkin #默认值为zipkin
  sleuth:
    sampler:
      percentage: 0.01 #(默认值为最低为1%)
    web:
      skip-pattern: /turbine.stream|/turbine.*|api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream
    scheduled:
      enabled: false
    integration:
      enabled: false

#admin显示日志信息配置
logging:
  path: /Users/yangtianfeng/Downloads/

#保护actuator接口
management:
  security:
    enabled: true
  context-path: /monitor

#请求参数校验
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
    path: /monotor/**
  enable-csrf: false


