server:
  port: 9007

spring:
  profiles: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clienttwo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
      #请求携带账户密码
  instance:
    metadata-map:
      user.name: admin
      user.password: admin
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
