spring:
  #admin客户端配置
  boot:
    admin:
      url: http://localhost:8001 #admin服务器地址
      client:
        metadata:
          user.name: admin       #actuor端点请求加密
          user.password: admin
  #zipkin客户端配置
  zipkin:
    enabled: true
    sender:
      type: rabbit
    rabbitmq:
      queue: monitor.zipkin #默认值为zipkin
  sleuth:
    web:
      skip-pattern: /turbine.stream|/turbine.*|api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream
    scheduled:
      skip-pattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask
    integration:
      enabled: false

#admin显示日志信息配置
logging:
  path: /Users/yangtianfeng/Downloads/

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: admin

