spring:
  #zipkin客户端配置
  zipkin:
    enabled: true
    sender:
      type: rabbit
    rabbitmq:
      queue: monitor.zipkin #默认值为zipkin
  sleuth:
    sampler:
      percentage: 0.001
    web:
      skip-pattern: /turbine.stream|/turbine.*|api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream
    scheduled:
      skip-pattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask
    integration:
      enabled: false

#admin显示日志信息配置
logging:
  path: /Users/yangtianfeng/Downloads/

management:
  security:
    enabled: false


