server:
  port: 4000

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

zuul:
  ignoredServices: '*'
  routes:
    service-a:
      path: /sa/**
      serviceId: client-one
    service-b:
      path: /sb/**
      serviceId: client-two
  host:
    connect-timeout-millis: 25000
    socket-timeout-millis: 5000

spring:
  profiles: demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest

ribbon:
  ReadTimeout: 4000
  SocketTimeout: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100

management:
  security:
    enabled: false




