turbine:
  stream:
    port: 8989 #指定turbine请求端口(0为随机可用端口)

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema[0]: classpath:/zipkin.sql
    initialize: false
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  sleuth:
    enabled: true

zipkin:
  ui:
    enabled: true
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: guest
      password: guest
      queue: monitor.zipkin  #默认值为zipkin
      concurrency: 1
  storage:
    type: mysql

