
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  boot:
    admin:
      #设置admin 请求前缀
      contextPath: /admin
      #服务发现配置
      discovery:
        ignored-services: monitor,registry
        converter:
          management-context-path: actuator
      #设置admin ui 模块
      routes:
        endpoints: "env,metrics,trace,dump,jolokia,info,loggers"
      #设置admin turbine
      turbine:
        clusters: "default,client-one"
        url: http://127.0.0.1:8001
      client:
        metadata:
          user.name: admin       #monitor请求admin携带账户密码
          user.password: admin

#actuator接口安全校验
management:
  security:
    enabled: true
  context-path: /actuator

endpoints:
  health:
    sensitive: true

security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true