
eureka:
  client:
    enabled: false

#基于eureka服务发现方式
spring:
  boot:
    admin:
      contextPath: /monitor
      turbine:
        clusters: "default"
        url: http://rrdloan-monitor.rrdbg.com/turbine/turbine.stream
  cloud:
    discovery:
      client:
        simple:
          instances:
            service-one:
            - uri: http://127.0.0.1:9006
              metadata:
                management.context-path: /

management:
  security:
    enabled: false #敏感端口无权访问，设置false则都可访问（acturcor）

security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
