server:
  port: 8761

spring:
  profiles: demo

eureka:
  instance:
    hostname: registry
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

